@expense_tracker.api_HostAddress = http://localhost:5153
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZGRpZW1vcmE3NEBnbWFpbC5jb20iLCJqdGkiOiJhNWZkYzIwNy00ZTdiLTRlYzctYjBkZS1kN2M1OWYyZmMxNTkiLCJpYXQiOjE3MzgwMjYyNTMsImV4cCI6MTczODAyNzQ1MywiaXNzIjoiRWRkaWVfRXhwZW5zZV9UcmFja2VyIiwiYXVkIjoiRWRkaWVfRXhwZW5zZV9UcmFja2VyX0F1ZGllbmNlIn0.aZWPzlMEbHasdu0SQ7G8Yl54XbBzUjegPXcPH4YqU-I

GET https://localhost:7231/api/expenses?filter=1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZGRpZW1vcmE3NEBnbWFpbC5jb20iLCJqdGkiOiI4NTJjMWVlOC0xZWZiLTRhMmEtYTQzMy0wZjg4ZjUzZjdkOTgiLCJpYXQiOjE3MzgxMTE3NDksImV4cCI6MTczOTgzOTc0OSwiaXNzIjoiRWRkaWVfRXhwZW5zZV9UcmFja2VyIiwiYXVkIjoiRWRkaWVfRXhwZW5zZV9UcmFja2VyX0F1ZGllbmNlIn0.lSJ9-RTDC2XfUwX6J-YE-nfepes4e2aJk83tRSti_qU

###

POST https://localhost:7231/api/expenses
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZGRpZW1vcmE3NEBnbWFpbC5jb20iLCJqdGkiOiI4NTJjMWVlOC0xZWZiLTRhMmEtYTQzMy0wZjg4ZjUzZjdkOTgiLCJpYXQiOjE3MzgxMTE3NDksImV4cCI6MTczOTgzOTc0OSwiaXNzIjoiRWRkaWVfRXhwZW5zZV9UcmFja2VyIiwiYXVkIjoiRWRkaWVfRXhwZW5zZV9UcmFja2VyX0F1ZGllbmNlIn0.lSJ9-RTDC2XfUwX6J-YE-nfepes4e2aJk83tRSti_qU

